### ISSUE TITLE
style:  making the code less complex in the http_util

### ISSUE THREAD

**Issue by RodrigoDornelles** [RodrigoDornelles/codename-videogame-engine#52]
It's quite messy because prioritizing finishing the functionality instead of being something readable, I'm too lazy to make a "string factory" but it would be what I would like in the final solution, in addition to being very reusable.

## features

 - [x] rename `http_util.headers()` to `http_util.create_request()`
 - [x] `http_util.craete_request()` must be return a object _(like pipeline, eg, `std.http.get`)_ 
 - [x] `add_body` shold not be used when method is `GET` or `HEAD`
 - [x] mutable header behavior is a default value can be changed by `add_custom_headers()`
 - [x] imutable headers shold not be modified by `add_custom_headers()`
 - [x] all headers add must be ordered with constructor
 - [x] headers should not be duplicated
 - [x] create a string result `toHttpProtocol()` for ginga
 - [x] create a string result `toCurlCommand()` for Curl protocol
 - [x] return values by `to...()` must be a string and function _(empty closujure)_
    - in the future a function must be a cleaner for temp files etc...

## Notes

- You can suggest other names that you think are more friendly
- It doesn't matter if you do <br/>`http_util.create_request():add_custom_header` or<br/>`http_util.create_request().add_custom_header`

### Protocol Ginga

</summary>

#### before

```lua
local headers = http_util.headers(self.header_list, self.header_dict, {
    'Host', self.p_host..params, false,
    'Accept', '*/*', true,
    'Cache-Control', 'max-age=0', false,
    'User-Agent', 'Mozilla/4.0 (compatible; MSIE 4.0; Windows 95; Win 9x 4.90)', true,
    'Content-Length', tostring(#self.body_content), false,
    'Connection', 'close', false
})
local request = 'GET '..self.p_uri..' HTTP/1.1\r\n'..headers..'\r\n'..self.body_content..'\r\n\r\n'
```

#### affter

```lua
local request = http.create_request(self.method)
    .add_imutable_header('Host', self.p_host..params)
    .add_imutable_header('Cache-control', 'max-age=0')
    .add_mutable_header('Accept', '*/*')
    .add_custom_headers(self.header_list, self.header_dict)
    .add_imutable_header('Connection', tostring(#self.body_content))
    .add_imutable_header('Content-Length', 'close')
    .add_body(self.body_content)
    .toHttpProtocol()
```

#### before

```lua
local index = 1
local cmd = 'curl -L \x2D\x2Dsilent \x2D\x2Dinsecure -w "\n%{http_code}" '
local protocol = self.method == 'HEAD' and '\x2D\x2DHEAD' or '-X ' .. self.method
local params = http_util.url_search_param(self.param_list, self.param_dict)

local headers, index = ' ', 1

while self.header_list and index <= #self.header_list do
    local header = self.header_list[index]
    headers = headers..'-H "'..header..': '
    headers = headers..self.header_dict[self.header_list[index]]..'" '
    index = index + 1
end

local body = ''
if self.method == 'POST' and self.body_content then
    body = '-d \''..self.body_content..'\' '
end


local request = cmd..protocol..headers..body..self.url..params
```

#### after

```lua
local request = http.create_request(self.method)
    .add_url_with_params(self.url, params)
    .add_custom_headers(self.header_list, self.header_dict)
    .add_body(self.body_content)
    .toCurlCommand()
```

**Comment by RodrigoDornelles** [comment]
I ended up closing PR #61 and #62, as they are very small, and it would be complex to deal with the tasks separately for both me and you @lnpotter .

I put this list of tasks more like a checklist, you can choose for each commit to be one, or just to confirm what remains to be done.

If you want it, and have the capacity to implement it completely, tell me about, and I hope you implement it! I was almost starting to do it because milestone [0.0.5](https://github.com/RodrigoDornelles/codename-videogame-engine/milestone/2) will be a lot of network updates.

**Comment by lnpotter** [comment]
I was going to try to implement it in isolation, to make it easier for me and you to understand. Do you want me to do it all at once? I can try, but my knowledge of Lua is shallow, @RodrigoDornelles.

**Comment by RodrigoDornelles** [comment]
@lnpotter 

This can be a single PR, and each topic can be a commit if you want to do it separately.

Here's a tip, when you use `:` in lua instead of `.` it passes the object into the function as the first parameter.

```lua
local function add_body(self, body)
   self.body = body
   return self -- pipeline tricky
end

local function myprint(self)
   print(self.body, self.method)
end

local function create_request(method)
   return {
      method=method,
      add_body=add_body,
      print=myprint
   }
end

create_request('get'):add_body('foo'):print()
```

You would need to implement some lists in terms of headers, if you find it very comfortable there are other [issues](https://github.com/RodrigoDornelles/codename-videogame-engine/issues?q=is%3Aissue+is%3Aopen+label%3A%22difficulty%3A+beginner%22) with less difficult levels, and I will try to implement this one.

**Comment by lnpotter** [comment]
Understood. I'll do it this way, then I'll create a PR with the respective changes in commits.
